import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import MixPanelProvider from "@/src/providers/mixpanel-provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MixPanelProvider>
        <body className={roboto.className}>{children}</body>
      </MixPanelProvider>
    </html>
  );
}
