#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo '🐶🐶 🏗️👷👷 Formatting, linting, and building your project before committing...'

# Define variables
PASS=0
FAIL=1

# Function to print a separator
print_separator() {
  echo "--------------------------------------------------"
}

# Formatting code
print_separator
echo "🔍🔍 Checking code formatting..."
if pnpm check:format; then
  echo -e "${GREEN}✅✅✅ Code formatting passed${NC}"
else
  echo -e "${RED}❌❌❌ Code formatting failed 🥶🥶🥶${NC}"
  exit $FAIL
fi

# Building code
print_separator
echo "🏗️🏗️ Building the project..."
if pnpm build; then
  echo -e "${GREEN}✅✅✅ Code building passed${NC}"
else
  echo -e "${RED}❌❌❌ Code building failed 🥶🥶🥶${NC}"
  exit $FAIL
fi

# All checks passed
print_separator
echo -e "${GREEN}✅💯 All checks passed${NC}"
echo -e "${GREEN}🎉🎉 Committing code now... ✔️✔️✔️${NC}"
exit $PASS