import MUIThemeProvider from "@/src/provider/theme-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MUIThemeProvider>
        <body>{children}</body>
      </MUIThemeProvider>
    </html>
  );
}
